Homework 20
Bilyk-VM/robot_dreams_homeworks pull request #14
Opened 2023-02-13 19:56 UTC by Bilyk-VM

Створення і наповнення баз данних

2023-02-16 19:36 UTC, klymenok requested changes
Check why files from 12 and 14 homework are here

2023-02-16 19:36 UTC, klymenok commented on 20/homework_20.2
> +     [
This won't work in the SQL console

2023-02-16 19:36 UTC, klymenok commented on 20/homework_20.4.py
> +             'first_name TEXT UNIQUE,'
`UNIQUE` here doesn't allow to add a first_name that already exists. For example, `John Snow` and `John Walker` are different names, but your table doesn't allow to add another John here.

To check for unique combinations you can use UNIQUE on the table level and set columns that should be unique together:
```
...
first_name TEXT,
last_name TEXT,
age INTEGER,
UNIQUE(first_name, last_name))

2023-02-20 21:05 UTC, klymenok commented on 20/homework_20.4.py
> +             'first_name TEXT UNIQUE,'
@Bilyk-VM you changed UNIQUE constraint in _20.4 file but didn't change it here as well

2023-02-21 19:37 UTC, Bilyk-VM commented
Комітив і випадково замість homework_20, написав  homework_22. Як змінити опис - дупля не бью, вже тут все облазив, ніяк не можу знайти як це зробити.

2023-02-26 14:51 UTC, klymenok approved these changes
Looks good!

2023-02-26 15:43 UTC, merged